# Generated by Selenium IDE
import time
import openpyxl
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import os
import pandas as pd


def waitlog(reason,timeout=20) :
  global driver
  for i in range(timeout) :
   x=driver.execute_script('return document.querySelector("#display-message").innerText')
   if reason.lower() in x.lower() :
       time.sleep(1)
   else :
       break
   if i==20 :
    print('failed please wait timeout')
    return 1/0
def credit(x,types='normal') :
   global a1
   global a2
   #print(x)
   if types=='fg' :
       return max(2,x[a2])
   if x[a1] < x[a2] :
      #print(x[a1],x[a2],1)
      return x[a2] 
   elif x[a1]==x[a2] :
      return max(1,x[a2])
   else :
        return max(1,x[a2])

   """if x[a1] > 1 :
       if x[a1]!=x[a2] :
           if x[a2]==0 :
               print(x[a1],x[a2],1)
               return 1
           else :
            print(x[a1],x[a2],x[a2])
            return x[a2]
       else :
           return x[a1] 
   else :
       if x[a2] > 1 and x[a1]<=1 :
           print(x[a1],x[a2],x[a2])
           return x[a2]
       else :
        return x[a1]"""
def waituntil(x,y=60) :
 global driver
 for i in range(y):
  try :
    driver.execute_script(x)
    break
  except:
    time.sleep(1)
    print(1,x)
 if i==y:
   try :
     driver.execute_script('document.querySelector("body > div.panel.window.ui-draggable.ui-resizable.ui-resizable-disabled.messager-window > div.dialog-button.messager-button > a").click();')    
     time.sleep(1)
     driver.execute_script(x)
   except :
    x=1/0
def waitclick(x) :
    for i in range(60) :
      try :
         driver.find_element(By.ID,x).click()
         break
      except :
         time.sleep(1)
def main() :
   global driver
   f=open('login.txt')
   userdata=eval(f.read())
   f.close()
   if int(userdata['headless'])==1 :
    driver.set_window_position(-10000,0)
   user,password,rs=userdata['usercredit'],userdata['passwordcredit'],userdata['rs']
   #user,password,rs='SA','Mosl1234@@','41A392'
   options = webdriver.ChromeOptions()
   options.add_argument("--window-size=1920,1080")
   options.add_argument("--start-maximized")
   options.add_argument("--user-data-dir=D:/vs/devaki enterprises/Profile 1")
   prefs = {'profile.managed_default_content_settings.images':2,'disk-cache-size':4096,'download.default_directory' : path }
   options.add_experimental_option('prefs', prefs)
   driver = webdriver.Chrome(r'chromedriver.exe',options=options)
   driver.maximize_window()
   driver.get('https://leveredge102.hulcd.com/rsunify/')
   searchbox = driver.find_element_by_xpath('//*[@id="userName"]')
   searchbox.send_keys(user)
   searchbox1 = driver.find_element_by_xpath('//*[@id="password"]')
   searchbox1.send_keys(password)
   searchbox = driver.find_element_by_xpath('//*[@id="databaseName"]')
   searchbox.send_keys(rs)
   but = driver.find_element_by_xpath('//*[@id="gologin"]')
   but.click()
   #checking for captcha and fro login loading main page 
   while True:
     try :
      driver.find_element(By.ID,"ikea_home_menu_search").send_keys("CREDIT LOCK")
      break
     except :
      captcha=driver.find_element(By.ID,'cap_question')
      captcha=captcha.get_attribute('innerText')
      captcha=captcha.replace('=','')
      captcha=captcha.split('+')
      try :
       captcha=[int(i.strip()) for i in captcha]
      except :
        time.sleep(0.5)
        continue
      value=sum(captcha)
      driver.execute_script('document.getElementById("cap_answer").value='+str(value))
      driver.execute_script('confirmSubmission();')
      WebDriverWait(driver,15).until(EC.element_to_be_clickable((By.ID,"ikea_home_menu_search"))).send_keys("CREDIT LOCK")
      break
   waituntil('document.querySelector("#search_menu_item_container > div:nth-child(1)").click();')
   driver.switch_to.window(driver.window_handles[1])
   def update(x) :
    waituntil('document.querySelector("#select1").click()')
    i=1
    while True :
        try :
          driver.execute_script('return document.querySelector("#D-'+str(i)+' > span").innerText')
          break
        except :
            time.sleep(0.5)
    
    driver.execute_script('document.querySelector("#beat-filter-search-popup > div.pnl-content > div:nth-child(1) > div > input").click()')
    time.sleep(1)
    driver.execute_script('document.querySelector("#beat-filter-search-popup > div.pnl-content > div:nth-child(1) > div > input").click()')
    time.sleep(1)
    for s in ["D","N","F","P","O"] :
     i=1
     while True :
       try:
        beat = driver.execute_script('return document.querySelector("#'+s+'-'+str(i)+' > span").innerText')
        print(beat,'tried')
       except :
           print('break')
           break
       print(beat,'FG' not in beat , 'WHOLESALE' not in beat ,'BEEMNAGAR'not in beat)
       if x=='FG' :
        if x not in beat and 'WHOLESALE' not in beat and 'BEEMNAGAR'not in beat  :
         waituntil('document.querySelector("#'+s+'-'+str(i)+' > input").click()')
         #time.sleep(1)
         print(beat,'allowed')
        else : 
           print(beat,'blocked')
       else :
          if 'FG' in beat and 'WHOLESALE' not in beat and 'BEEMNAGAR'not in beat  :
           waituntil('document.querySelector("#'+s+'-'+str(i)+' > input").click()')
           #time.sleep(1)
           print(beat,'allowed')
          else : 
           print(beat,'blocked')
       i=i+1
    waituntil('document.querySelector("#beat-filter-search-popup > div.pnl-header > div > a").click()')
    intial = os.listdir(path)
    waituntil('GenerateMethod()')
    while True :
        if len(os.listdir(path)) == len(intial)+1 :
           filename=(set(os.listdir(path))^set(intial))&set(os.listdir(path))
           if 'tmp' not in filename and 'crd' not in filename :
               break
           else :
               time.sleep(1)
        else :
           time.sleep(1)
    time.sleep(1)
    print('download succes')
    #time.sleep(200)
    while True :
      try :
        filename=(set(os.listdir(path))^set(intial))&set(os.listdir(path))
        df=pd.read_excel(path+list(filename)[0])
        break
      except :
          time.sleep(1)
    global a1
    global a2
    a1=df.columns[5]
    a2=df.columns[8]
    print(2)
    df1=[]
    df.to_excel('a.xlsx')
    for idx,row in df.iterrows() :
        row1=row
        if x!='FG' :
         row1[a1]=credit(row,'fg')
        else :
            row1[a1]=credit(row)
        df1.append(row1)
    df1=pd.DataFrame(df1)
    filename=list(set(filename))[0] 
    wb = openpyxl.load_workbook(path+filename)
    ws = wb['Credit Locking']
    startcol = 6
    startrow = 2
    for item in df1[df1.columns[5]]:
     ws.cell(startrow, startcol).value = item
     startrow +=1
    wb.save(path+filename)
    driver.find_element(By.ID,"attach_file").send_keys(path+filename)
    driver.execute_script("uploadMethod();")
    while True :
      if 'Uploaded' in driver.execute_script('return document.querySelector("#display-message").innerText') :
          print('Finished')
          #time.sleep(10)
          #driver.quit()
          break
      else :
          time.sleep(1)
   update('FG')
   update('abcdefg')
   time.sleep(10)
   driver.quit()
path='D:\\credit\\'    
a1,a2='','' 
#main()
  
  
