# Generated by Selenium IDE
import time
import openpyxl
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import os
from IMP.main import  *
import pandas as pd
import win32com.client as win32
import datetime

def main() :
   driver = login(path)
   date  = datetime.datetime.now() - datetime.timedelta(days=1)
   data = data_ajax(driver,"getmarketorder",{"url" : "/rsunify/app/quantumImport/validateload.do","importdate":date.strftime("%Y-%m-%d"),
                                      "orderdate":date.strftime("%Y-%m-%d")})
   data = [itm["parName"]  for itm in data["quantumImportList"] if itm["assignQty"] != 0 ]
   partys = list(set(data))
   partys = [ party.split('-')[0] for party in partys]
   if len(partys) == 0 : 
       print("None present")
       return 0
   print(partys)
   replaces = {'beatkeys':''}
   fpath = report_ajax(driver,'creditlockdown',replaces,make_download=True)
   def filter_excel(fpath,partys) :
       df = pd.read_excel(fpath)
       df = df.astype({'Sr No':str})
       df = df[df['PAR NAME'].apply(lambda x : x.split('-')[0] in partys)]
       df = df[df.apply(lambda row : (row['PAR CR BILLS'] <= row["PAR CR BILLS UTILISED"]) and row['PAR CR BILLS']!=0 ,axis=1)]
       df.to_excel(fpath,index=False)
       print("Finsihed credit lock filter")
       if len(df['PAR NAME']) == 0 : 
           print("None present")
           return True
   def upload(fpath):
    driver.find_element(By.ID,"attach_file").send_keys(fpath)
    driver.execute_script("uploadMethod();")
    while True :
      if 'Uploaded' in driver.execute_script('return document.querySelector("#display-message").innerText') :
          print('Finished',fpath)
          break
      else :
          time.sleep(0.5)
   if filter_excel(fpath,partys) :
       return 0 
   OpenExcel(fpath) 
   WebDriverWait(driver,15).until(EC.element_to_be_clickable((By.ID,"ikea_home_menu_search"))).send_keys("CREDIT LOCK") #open credit lock for uploading 
   waituntil(driver,'document.querySelector("#search_menu_item_container > div:nth-child(1)").click();')
   driver.switch_to.window(driver.window_handles[1])
   while input("press y after finishing S: ") != 'y' :
       continue 
   upload(fpath)
   driver.close()
   driver.quit()
   return "FINISHED UPLOADING"

path='D:\\credit\\'    

  
  
